### ISSUE TITLE
Composer install broken

### ISSUE THREAD

**Issue by webfractor** [aparticka/laravel-auth-ldap#3]
I think adlap/adldap might have borked you, but when I add you to my composer.json

```
"require": {
    "aparticka/laravel-auth-ldap": "dev-master"
}
```

I get Problems

```
 Problem 1
    - Installation request for aparticka/laravel-auth-ldap dev-master -> satisfiable by aparticka/laravel-auth-ldap[dev-master].
    - aparticka/laravel-auth-ldap dev-master requires adldap/adldap ~4.0 -> no matching package found.
```

**Comment by aparticka** [comment]
Looks like all of the tags for adlap/adldap were removed from Packagist other than `dev-master`. I'll update the `composer.json` for now and keep an eye on it.

**Comment by webfractor** [comment]
cool, I opened an issue with adlap/adlap about this as well.

https://github.com/adldap/adLDAP/issues/79

**Comment by webfractor** [comment]
thanks!
